<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Picqer\\Barcode\\' => array($vendorDir . '/picqer/php-barcode-generator/src'),
    'PHPBarcode\\' => array($vendorDir . '/dvdmarchetti/phpbarcode/src/PHPBarcode'),
);
