<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit94c2e07165a410c67a6819a16cfbaf7f
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Picqer\\Barcode\\' => 15,
            'PHPBarcode\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Picqer\\Barcode\\' => 
        array (
            0 => __DIR__ . '/..' . '/picqer/php-barcode-generator/src',
        ),
        'PHPBarcode\\' => 
        array (
            0 => __DIR__ . '/..' . '/dvdmarchetti/phpbarcode/src/PHPBarcode',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit94c2e07165a410c67a6819a16cfbaf7f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit94c2e07165a410c67a6819a16cfbaf7f::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit94c2e07165a410c67a6819a16cfbaf7f::$classMap;

        }, null, ClassLoader::class);
    }
}
